"""Convert LaRS panoptic 'thing' instances into YOLOv8-seg polygon labels.

Same 8 typed classes as scripts/lars/export_yolo_det.py, but emits per-instance
POLYGONS (ultralytics seg format: `cls x1 y1 x2 y2 ... xn yn`, normalised) by
contouring each instance in the panoptic mask (COCO encoding id = R+256G+65536B,
matched to panoptic_annotations.json segments_info). Generates LABELS ONLY so it
can reuse the images already exported by export_yolo_det.py (identical frames).

    python -m scripts.lars.export_yolo_seg --out data/lars_yolo_seg --splits train,val
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import cv2
import numpy as np
from PIL import Image

from scripts.lars.export_yolo_det import CATID_TO_YOLO, NAMES, DEFAULT_LARS_ROOT


def _panoptic_paths(root: Path, split: str):
    j = root / "lars_v1.0.0_annotations" / split / "panoptic_annotations.json"
    masks = root / "lars_v1.0.0_annotations" / split / "panoptic_masks"
    return j, masks


def instance_polygons(mask_bin: np.ndarray, W: int, H: int,
                      min_area: int = 25, eps_frac: float = 0.004) -> list[list[float]]:
    """Return normalised polygons for a binary instance mask (largest parts)."""
    cnts, _ = cv2.findContours(mask_bin, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    polys: list[list[float]] = []
    for c in cnts:
        if cv2.contourArea(c) < min_area:
            continue
        eps = eps_frac * cv2.arcLength(c, True)
        ap = cv2.approxPolyDP(c, eps, True).reshape(-1, 2)
        if len(ap) < 3:
            continue
        flat: list[float] = []
        for x, y in ap:
            flat.append(min(max(x / W, 0.0), 1.0))
            flat.append(min(max(y / H, 0.0), 1.0))
        polys.append(flat)
    return polys


def convert_split(root: Path, out: Path, split: str, limit: int | None) -> tuple[int, int]:
    pj, masks_dir = _panoptic_paths(root, split)
    data = json.loads(pj.read_text())
    images = {im["id"]: im for im in data["images"]}
    out_lbl = out / "labels" / split
    out_lbl.mkdir(parents=True, exist_ok=True)

    anns = data["annotations"]
    if limit is not None:
        anns = anns[:limit]
    n_img = n_obj = 0
    for k, ann in enumerate(anns):
        im = images.get(ann["image_id"])
        if im is None:
            continue
        W, H = int(im["width"]), int(im["height"])
        stem = Path(im["file_name"]).stem
        mpath = masks_dir / ann["file_name"]
        if not mpath.exists():
            continue
        arr = np.array(Image.open(mpath))[:, :, :3].astype(np.int64)
        ids = arr[:, :, 0] + 256 * arr[:, :, 1] + 65536 * arr[:, :, 2]

        lines: list[str] = []
        for seg in ann["segments_info"]:
            yi = CATID_TO_YOLO.get(seg["category_id"])
            if yi is None:
                continue
            mask_bin = (ids == seg["id"]).astype(np.uint8)
            for poly in instance_polygons(mask_bin, W, H):
                coords = " ".join(f"{v:.5f}" for v in poly)
                lines.append(f"{yi} {coords}")
                n_obj += 1
        (out_lbl / f"{stem}.txt").write_text("\n".join(lines) + ("\n" if lines else ""))
        n_img += 1
        if (k + 1) % 300 == 0:
            print(f"  [{split}] {k + 1}/{len(anns)}", file=sys.stderr, flush=True)
    return n_img, n_obj


def write_data_yaml(out: Path, images_rel: str = "images") -> Path:
    p = out / "data.yaml"
    names_block = "\n".join(f"  {i}: {n}" for i, n in enumerate(NAMES))
    p.write_text(
        "# Auto-generated by scripts/lars/export_yolo_seg.py (YOLOv8-seg)\n"
        f"path: {out.resolve()}\n"
        f"train: {images_rel}/train\n"
        f"val: {images_rel}/val\n"
        f"nc: {len(NAMES)}\n"
        "names:\n" + names_block + "\n"
    )
    return p


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--lars-root", type=Path, default=DEFAULT_LARS_ROOT)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--splits", default="train,val")
    ap.add_argument("--limit", type=int, default=None)
    args = ap.parse_args(argv)
    print(f"LaRS root: {args.lars_root}\nOut(labels): {args.out}\nClasses: {NAMES}")
    for split in [s.strip() for s in args.splits.split(",") if s.strip()]:
        ni, no = convert_split(args.lars_root, args.out, split, args.limit)
        print(f"  {split}: {ni} images, {no} instance polygons")
    write_data_yaml(args.out)
    print("done")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
