"""Convert LaRS panoptic 'thing' instances into a YOLO detection dataset.

LaRS panoptic annotations carry 8 typed object ("thing") classes with per-
instance COCO bboxes (panoptic_annotations.json -> segments_info). This builds a
standard YOLO detector dataset from them so the existing GPU pipeline
(scripts/gpu_finetune/train_yolo.py) can train a typed detector
(boat/swimmer/buoy/...). Distinct from scripts/lars/prepare.py, which stages the
3-class *semantic* masks for eWaSR (the range fix).

YOLO labels are normalised (cx cy w h in [0,1]), so images may be downscaled
freely (`--max-side`) without touching the labels; keeps the upload small and
training fast. Images with no thing instances are kept as background negatives
(empty label file), which helps suppress false positives.

Output:
    <out>/images/{train,val}/<stem>.jpg
    <out>/labels/{train,val}/<stem>.txt      # "cls cx cy w h" per object
    <out>/data.yaml                          # ultralytics dataset spec

    python -m scripts.lars.export_yolo_det \
        --lars-root /Volumes/ROS2_SSD/LaRS_v1.0.0 --out data/lars_yolo --max-side 1280
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from PIL import Image

DEFAULT_LARS_ROOT = Path("/Volumes/ROS2_SSD/LaRS_v1.0.0")

# LaRS thing category_id -> (yolo_index, name). Order follows the category ids.
THING_CLASSES = [
    (11, "boat_ship"),
    (12, "row_boats"),
    (13, "paddle_board"),
    (14, "buoy"),
    (15, "swimmer"),
    (16, "animal"),
    (17, "float"),
    (19, "other"),
]
CATID_TO_YOLO = {cat: i for i, (cat, _name) in enumerate(THING_CLASSES)}
NAMES = [name for _cat, name in THING_CLASSES]


def _panoptic_json(root: Path, split: str) -> Path:
    return root / "lars_v1.0.0_annotations" / split / "panoptic_annotations.json"


def _image_path(root: Path, split: str, file_name: str) -> Path:
    return root / "lars_v1.0.0_images" / split / "images" / file_name


def convert_split(
    root: Path, out: Path, split: str, max_side: int, limit: int | None
) -> tuple[int, int]:
    """Returns (#images written, #object instances written)."""
    pj = _panoptic_json(root, split)
    if not pj.exists():
        raise FileNotFoundError(f"missing {pj}")
    data = json.loads(pj.read_text())
    images = {im["id"]: im for im in data["images"]}

    out_img = out / "images" / split
    out_lbl = out / "labels" / split
    out_img.mkdir(parents=True, exist_ok=True)
    out_lbl.mkdir(parents=True, exist_ok=True)

    anns = data["annotations"]
    if limit is not None:
        anns = anns[:limit]

    n_img = n_obj = 0
    for k, ann in enumerate(anns):
        im = images.get(ann["image_id"])
        if im is None:
            continue
        W, H = float(im["width"]), float(im["height"])
        src = _image_path(root, split, im["file_name"])
        if not src.exists():
            continue
        stem = Path(im["file_name"]).stem

        lines: list[str] = []
        for seg in ann["segments_info"]:
            yi = CATID_TO_YOLO.get(seg["category_id"])
            if yi is None:                       # stuff class -> skip
                continue
            x, y, w, h = seg["bbox"]             # COCO xywh, pixels
            if w <= 0 or h <= 0:
                continue
            cx = (x + w / 2.0) / W
            cy = (y + h / 2.0) / H
            nw, nh = w / W, h / H
            # clamp into [0,1] (a few boxes touch the border)
            cx, cy = min(max(cx, 0.0), 1.0), min(max(cy, 0.0), 1.0)
            nw, nh = min(nw, 1.0), min(nh, 1.0)
            lines.append(f"{yi} {cx:.6f} {cy:.6f} {nw:.6f} {nh:.6f}")
            n_obj += 1

        # Write image (optionally downscaled; labels are normalised so unchanged).
        img = Image.open(src).convert("RGB")
        if max_side and max(img.size) > max_side:
            scale = max_side / max(img.size)
            img = img.resize((round(img.width * scale), round(img.height * scale)),
                             Image.BILINEAR)
        img.save(out_img / f"{stem}.jpg", quality=92)
        (out_lbl / f"{stem}.txt").write_text("\n".join(lines) + ("\n" if lines else ""))
        n_img += 1
        if (k + 1) % 300 == 0:
            print(f"  [{split}] {k + 1}/{len(anns)}", file=sys.stderr, flush=True)

    return n_img, n_obj


def write_data_yaml(out: Path) -> Path:
    p = out / "data.yaml"
    names_block = "\n".join(f"  {i}: {n}" for i, n in enumerate(NAMES))
    p.write_text(
        "# Auto-generated by scripts/lars/export_yolo_det.py\n"
        f"path: {out.resolve()}\n"
        "train: images/train\n"
        "val: images/val\n"
        f"nc: {len(NAMES)}\n"
        "names:\n" + names_block + "\n"
    )
    return p


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--lars-root", type=Path, default=DEFAULT_LARS_ROOT)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--splits", default="train,val")
    ap.add_argument("--max-side", type=int, default=1280, help="downscale cap (0=keep native)")
    ap.add_argument("--limit", type=int, default=None)
    args = ap.parse_args(argv)

    print(f"LaRS root: {args.lars_root}\nOut: {args.out}\nClasses: {NAMES}")
    for split in [s.strip() for s in args.splits.split(",") if s.strip()]:
        print(f"Converting {split} ...")
        ni, no = convert_split(args.lars_root, args.out, split, args.max_side, args.limit)
        print(f"  {split}: {ni} images, {no} object instances")
    cfg = write_data_yaml(args.out)
    print(f"data.yaml -> {cfg}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
