#!/usr/bin/env bash
# Runs ON THE GPU NODE. Builds a scratch venv with vLLM + Qwen-VL deps, points
# all caches at scratch, pre-downloads the model, and writes an activation shim.
#
# Idempotent: safe to re-run. Invoked by 03_setup_gpu.sh, or by hand:
#   bash ~/asvproject_project/ASVProject-ObstacleDetection/scripts/gpu_labeling/setup_scratch_labeling.sh [MODEL]
set -euo pipefail

LABEL_SCRATCH="${LABEL_SCRATCH:-/scratch0/${USER}/asvproject}"
MODEL="${1:-${MODEL:-Qwen/Qwen3-VL-8B-Instruct-FP8}}"

VENV_DIR="${LABEL_SCRATCH}/labeling_venv"
CACHE_DIR="${LABEL_SCRATCH}/.cache"
SHIM="${LABEL_SCRATCH}/activate_labeling.sh"
CODE_DIR="${HOME}/asvproject_project/ASVProject-ObstacleDetection"
REQ_FILE="${CODE_DIR}/requirements-gpu.txt"

echo "Scratch : ${LABEL_SCRATCH}"
echo "Venv    : ${VENV_DIR}"
echo "Model   : ${MODEL}"
echo ""

# --- Redirect ALL caches to scratch BEFORE any pip/uv/HF operation ---
export PIP_CACHE_DIR="${CACHE_DIR}/pip"
export UV_CACHE_DIR="${CACHE_DIR}/uv"
export HF_HOME="${CACHE_DIR}/huggingface"
export HF_HUB_CACHE="${CACHE_DIR}/huggingface/hub"
export TORCH_HOME="${CACHE_DIR}/torch"
export UV_PROJECT_ENVIRONMENT="${VENV_DIR}"
mkdir -p "${VENV_DIR}" "${PIP_CACHE_DIR}" "${UV_CACHE_DIR}" \
         "${HF_HUB_CACHE}" "${TORCH_HOME}" "${LABEL_SCRATCH}/out"

# --- GPU visible? ---
nvidia-smi --query-gpu=name,memory.total --format=csv,noheader || {
  echo "ERROR: nvidia-smi failed, not on a GPU node?"; exit 1; }

# --- uv (fast installer); fall back to python venv + pip ---
if ! command -v uv &>/dev/null; then
  echo "Installing uv to scratch ..."
  export CARGO_HOME="${LABEL_SCRATCH}/.cargo"
  curl -LsSf https://astral.sh/uv/install.sh | \
    env INSTALLER_NO_MODIFY_PATH=1 UV_INSTALL_DIR="${LABEL_SCRATCH}/bin" sh
  export PATH="${LABEL_SCRATCH}/bin:${PATH}"
fi

echo ""
echo "Creating venv + installing deps (this is the slow step) ..."
if command -v uv &>/dev/null; then
  [[ -x "${VENV_DIR}/bin/python" ]] || uv venv "${VENV_DIR}" --python 3.11
  # shellcheck source=/dev/null
  source "${VENV_DIR}/bin/activate"
  uv pip install --upgrade pip wheel
  uv pip install -r "${REQ_FILE}"
else
  [[ -x "${VENV_DIR}/bin/python" ]] || python3 -m venv "${VENV_DIR}"
  # shellcheck source=/dev/null
  source "${VENV_DIR}/bin/activate"
  pip install --upgrade pip wheel
  pip install -r "${REQ_FILE}"
fi

echo ""
echo "Verifying torch + CUDA ..."
python - <<'PY'
import torch
print("torch:", torch.__version__, "cuda:", torch.cuda.is_available(),
      torch.cuda.get_device_name(0) if torch.cuda.is_available() else "(no cuda)")
try:
    import vllm; print("vllm:", vllm.__version__)
except Exception as e:
    print("vllm import failed:", e)
PY

echo ""
echo "Pre-downloading model: ${MODEL} (let HF_HOME manage paths) ..."
python - "${MODEL}" <<'PY'
import sys
from huggingface_hub import snapshot_download
m = sys.argv[1]
snapshot_download(m)
print("downloaded:", m)
PY

# --- Write activation shim sourced by 04_run_labeling.sh ---
cat > "${SHIM}" <<EOF
#!/usr/bin/env bash
# Auto-generated by setup_scratch_labeling.sh: source before running the labeler.
export PATH="${LABEL_SCRATCH}/bin:\$PATH"
export PIP_CACHE_DIR="${CACHE_DIR}/pip"
export UV_CACHE_DIR="${CACHE_DIR}/uv"
export HF_HOME="${CACHE_DIR}/huggingface"
export HF_HUB_CACHE="${CACHE_DIR}/huggingface/hub"
export TORCH_HOME="${CACHE_DIR}/torch"
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
# These nodes ship the CUDA *runtime* (torch sees the GPU) but no CUDA toolkit
# (no nvcc). FlashInfer JIT-compiles its sampler kernels with nvcc and therefore
# fails, so disable it: vLLM falls back to its prebuilt FlashAttention + native
# sampler (attention init succeeds without nvcc).
export VLLM_USE_FLASHINFER_SAMPLER=0
source "${VENV_DIR}/bin/activate"
echo "Qwen labelling env activated (venv: ${VENV_DIR})."
EOF
chmod +x "${SHIM}"

echo ""
echo "Setup complete. Shim: ${SHIM}"
