/* Export the dashboard's curation (public.sail_curation) to the git-tracked
 * configs/curation.yaml that the Python side reads (scripts/utils/curation.py:
 * list_triplets, iterate_triplet, the baker, build_features, the planner).
 *
 * Only sets that carry curation are written: deleted (incl. purged) sets and
 * sets with at least one cut. A restored set with no cuts is simply absent.
 * Each set lists its member chunks (from the catalogue when the key is an
 * activity; the key's own timestamp otherwise) so chunk-level consumers
 * resolve activity-level decisions.
 *
 * Usage (from dashboard/, env from .env.local):
 *   pnpm curation:export [--out ../configs/curation.yaml]
 */

import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { CurationRecordSchema, type CurationRecord } from "../../lib/curation/types";
import { isDeleted } from "../../lib/curation/logic";
import { loadEnvLocal, option, REPO_ROOT, supabaseAdmin } from "./env";

const q = (s: string) => JSON.stringify(s); // JSON strings are valid YAML scalars

/** Deterministic YAML emitter for the curation schema (pure; tested). */
export function renderCurationYaml(
  records: CurationRecord[],
  chunksByKey: Map<string, string[]>,
  exportedAt: string,
): string {
  const lines: string[] = [
    "# configs/curation.yaml — GENERATED by `pnpm curation:export`",
    "# (dashboard/tools/curation/export.ts) from the dashboard's sail_curation",
    "# table. Do not hand-edit: delete / restore / trim sets in the dashboard,",
    "# then re-export and commit. Schema: docs/reference/data_formats.md §6.",
    "#",
    "# A set is DELETED when deleted_at is set and not restored since, or when",
    "# purged_at is set (bundle removed by `pnpm curation:prune`). Cuts are",
    "# inclusive frame-id timestamp ranges (HH:MM:SS.f); frame ids never change.",
    "# Nothing here deletes files: raw captures on the SSD are untouched.",
    "version: 1",
    `exported_at: ${q(exportedAt)}`,
  ];
  const kept = records
    .filter((r) => isDeleted(r) || r.cuts.length > 0)
    .sort((a, b) => a.clip_key.localeCompare(b.clip_key));
  if (kept.length === 0) {
    lines.push("sets: {}");
    return lines.join("\n") + "\n";
  }
  lines.push("sets:");
  for (const r of kept) {
    const own = r.clip_key.split("__").slice(1).join("__");
    const chunks = chunksByKey.get(r.clip_key) ?? [own];
    lines.push(`  ${q(r.clip_key)}:`);
    lines.push(`    deleted_at: ${r.deleted_at ? q(r.deleted_at) : "null"}`);
    lines.push(`    restored_at: ${r.restored_at ? q(r.restored_at) : "null"}`);
    lines.push(`    purged_at: ${r.purged_at ? q(r.purged_at) : "null"}`);
    lines.push(`    chunks: [${chunks.map(q).join(", ")}]`);
    if (r.cuts.length === 0) {
      lines.push("    cuts: []");
    } else {
      lines.push("    cuts:");
      for (const c of r.cuts) {
        const note = c.note ? `, note: ${q(c.note)}` : "";
        lines.push(`      - {start_ts: ${q(c.start_ts)}, end_ts: ${q(c.end_ts)}${note}}`);
      }
    }
    if (r.note) lines.push(`    note: ${q(r.note)}`);
    if (r.updated_by) lines.push(`    updated_by: ${q(r.updated_by)}`);
  }
  return lines.join("\n") + "\n";
}

async function main(): Promise<number> {
  loadEnvLocal();
  const supabase = supabaseAdmin();
  const out = path.resolve(option("--out") ?? path.join(REPO_ROOT, "configs", "curation.yaml"));

  const { data: rows, error } = await supabase.from("sail_curation").select("*");
  if (error) throw new Error(`sail_curation select: ${error.message}`);
  const records = (rows ?? [])
    .map((r) => CurationRecordSchema.safeParse(r))
    .filter((p) => p.success)
    .map((p) => p.data);

  const { data: clips, error: clipErr } = await supabase
    .from("sail_clips")
    .select("clip_key, summary");
  if (clipErr) throw new Error(`sail_clips select: ${clipErr.message}`);
  const chunksByKey = new Map<string, string[]>();
  for (const c of clips ?? []) {
    const s = c.summary as { chunks?: string[]; triplet_ts?: string };
    const chunks = s.chunks?.length ? s.chunks : s.triplet_ts ? [s.triplet_ts] : [];
    if (chunks.length) chunksByKey.set(c.clip_key as string, chunks);
  }

  const yaml = renderCurationYaml(records, chunksByKey, new Date().toISOString());
  mkdirSync(path.dirname(out), { recursive: true });
  writeFileSync(out, yaml);
  const nDeleted = records.filter(isDeleted).length;
  const nTrimmed = records.filter((r) => !isDeleted(r) && r.cuts.length > 0).length;
  console.log(
    `wrote ${out}: ${records.length} record(s) -> ${nDeleted} deleted, ${nTrimmed} trimmed ` +
    `(${records.length - nDeleted - nTrimmed} restored/no-op omitted)`,
  );
  return 0;
}

const isDirect = process.argv[1] && path.resolve(process.argv[1]) === path.resolve(new URL(import.meta.url).pathname);
if (isDirect) {
  main().then(
    (code) => process.exit(code),
    (err) => {
      console.error(err);
      process.exit(1);
    },
  );
}
