#!/usr/bin/env bash
# Runs ON THE GPU NODE. Builds a scratch venv with torch (cu118) + eWaSR deps,
# points all caches at scratch, clones eWaSR, downloads the pretrained MaSTr
# weights, and writes an activation shim.
#
# Idempotent: safe to re-run. Invoked by 03_setup_gpu.sh, or by hand:
#   SEG_SCRATCH=/scratch0/$USER/asvproject_seg \
#     bash ~/asvproject_project/ASVProject-ObstacleDetection/scripts/gpu_seg/setup_scratch_seg.sh
set -euo pipefail

SEG_SCRATCH="${SEG_SCRATCH:-/scratch0/${USER}/asvproject_seg}"
EWASR_REPO="${EWASR_REPO:-https://github.com/tersekmatija/eWaSR.git}"
PRETRAINED_URL="${PRETRAINED_URL:-https://github.com/tersekmatija/eWaSR/releases/download/0.1.0/ewasr_resnet18.pth}"

VENV_DIR="${SEG_SCRATCH}/seg_venv"
CACHE_DIR="${SEG_SCRATCH}/.cache"
EWASR_DIR="${SEG_SCRATCH}/eWaSR"
WEIGHTS_DIR="${SEG_SCRATCH}/weights"
SHIM="${SEG_SCRATCH}/activate_seg.sh"
CODE_DIR="${HOME}/asvproject_project/ASVProject-ObstacleDetection"
REQ_FILE="${CODE_DIR}/requirements-gpu-seg.txt"

echo "Scratch : ${SEG_SCRATCH}"
echo "Venv    : ${VENV_DIR}"
echo "eWaSR   : ${EWASR_DIR}"
echo ""

# --- Redirect ALL caches to scratch BEFORE any pip/HF/torch operation ---
export PIP_CACHE_DIR="${CACHE_DIR}/pip"
export HF_HOME="${CACHE_DIR}/huggingface"
export TORCH_HOME="${CACHE_DIR}/torch"
export XDG_CACHE_HOME="${CACHE_DIR}/xdg"
mkdir -p "${VENV_DIR}" "${PIP_CACHE_DIR}" "${TORCH_HOME}" "${XDG_CACHE_HOME}" \
         "${WEIGHTS_DIR}" "${SEG_SCRATCH}/runs"

# --- GPU visible? ---
nvidia-smi --query-gpu=name,memory.total --format=csv,noheader || {
  echo "ERROR: nvidia-smi failed, not on a GPU node?"; exit 1; }

# --- uv (fast installer); fall back to python venv + pip ---
if ! command -v uv &>/dev/null; then
  echo "Installing uv to scratch ..."
  curl -LsSf https://astral.sh/uv/install.sh | \
    env INSTALLER_NO_MODIFY_PATH=1 UV_INSTALL_DIR="${SEG_SCRATCH}/bin" sh
  export PATH="${SEG_SCRATCH}/bin:${PATH}"
fi
export UV_CACHE_DIR="${CACHE_DIR}/uv"

echo ""
echo "Creating venv (python 3.11) + installing deps (slow step) ..."
if command -v uv &>/dev/null; then
  [[ -x "${VENV_DIR}/bin/python" ]] || uv venv "${VENV_DIR}" --python 3.11
  # shellcheck source=/dev/null
  source "${VENV_DIR}/bin/activate"
  uv pip install --upgrade pip wheel "setuptools<81"
  # torch FIRST, from the cu118 wheel index (node driver 560 runs cu118 fine).
  uv pip install torch==2.0.1 torchvision==0.15.2 --index-url https://download.pytorch.org/whl/cu118
  uv pip install -r "${REQ_FILE}"
else
  [[ -x "${VENV_DIR}/bin/python" ]] || python3 -m venv "${VENV_DIR}"
  # shellcheck source=/dev/null
  source "${VENV_DIR}/bin/activate"
  pip install --upgrade pip wheel "setuptools<81"
  pip install torch==2.0.1 torchvision==0.15.2 --index-url https://download.pytorch.org/whl/cu118
  pip install -r "${REQ_FILE}"
fi

echo ""
echo "Verifying torch + CUDA ..."
python - <<'PY'
import torch
print("torch:", torch.__version__, "cuda:", torch.cuda.is_available(),
      torch.cuda.get_device_name(0) if torch.cuda.is_available() else "(no cuda)")
import pytorch_lightning as pl
print("pytorch_lightning:", pl.__version__)
PY

# --- Clone / update eWaSR ---
echo ""
if [[ -d "${EWASR_DIR}/.git" ]]; then
  echo "eWaSR repo present; pulling ..."
  git -C "${EWASR_DIR}" pull --ff-only || true
else
  echo "Cloning eWaSR ..."
  git clone --depth 1 "${EWASR_REPO}" "${EWASR_DIR}"
fi

# --- Pretrained MaSTr weights (for immediate inference baseline) ---
echo ""
PRETRAINED_PTH="${WEIGHTS_DIR}/ewasr_resnet18_mastr.pth"
if [[ ! -s "${PRETRAINED_PTH}" ]]; then
  echo "Downloading pretrained MaSTr weights ..."
  curl -L -o "${PRETRAINED_PTH}" "${PRETRAINED_URL}" || \
    echo "WARNING: pretrained download failed (LaRS-trained weights will still work)."
else
  echo "Pretrained weights already present."
fi

# --- Write activation shim sourced by 04_train.sh / 05_predict.sh ---
cat > "${SHIM}" <<EOF
#!/usr/bin/env bash
# Auto-generated by setup_scratch_seg.sh: source before training/predicting.
export PATH="${SEG_SCRATCH}/bin:\$PATH"
export PIP_CACHE_DIR="${CACHE_DIR}/pip"
export UV_CACHE_DIR="${CACHE_DIR}/uv"
export HF_HOME="${CACHE_DIR}/huggingface"
export TORCH_HOME="${CACHE_DIR}/torch"
export XDG_CACHE_HOME="${CACHE_DIR}/xdg"
# NOTE: do not set PYTORCH_CUDA_ALLOC_CONF=expandable_segments: that option
# only exists in torch>=2.1, and this venv pins torch 2.0.1 (PL 1.x compat).
source "${VENV_DIR}/bin/activate"
echo "eWaSR seg env activated (venv: ${VENV_DIR})."
EOF
chmod +x "${SHIM}"

echo ""
echo "Setup complete. Shim: ${SHIM}"
echo "  eWaSR    : ${EWASR_DIR}"
echo "  weights  : ${PRETRAINED_PTH}"
